[package]
name = "dungeon"
version = "0.4.2"
edition = "2021"

[dependencies]
indoc = "2.0.5"
input-macro = "0.2.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
split-debuginfo = "off"
strip = true
